server:
  port: 10010
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/**
    search-service: /search/**
  ignored-services:
    - upload-service # 忽略upload-service服务
ribbon:
  ConnectTimeout: 2500000 # 连接超时时间(ms)
  ReadTimeout: 2000000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 10 # 同一服务不同实例的重试次数
  MaxAutoRetries: 2 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 100000000 # 熔断超时时长：10000ms
